# Auto-generated by threshold_distiller.py
from __future__ import annotations

FEATURES = ['profile_mean', 'profile_stdev', 'profile_skewness', 'profile_kurtosis', 'dm_snr_mean', 'dm_snr_stdev', 'dm_snr_skewness', 'dm_snr_kurtosis']
MODEL_INFO = {'method': 'threshold_distiller', 'model_family': 'sklearn.GradientBoostingClassifier', 'selection_mode': 'val', 'overfit_penalty': 1.0, 'selected_rank_by_stable_val': 7, 'function': 'fn_p', 'length': 8, 'train_size': 256, 'val_size': 256, 'test_size': 2000, 'seed': 42, 'tabular_representation': 'named_numeric', 'features': ['profile_mean', 'profile_stdev', 'profile_skewness', 'profile_kurtosis', 'dm_snr_mean', 'dm_snr_stdev', 'dm_snr_skewness', 'dm_snr_kurtosis'], 'params': {'n_estimators': 10, 'learning_rate': 0.3, 'max_depth': 3, 'min_samples_leaf': 10}, 'train_acc': 0.9765625, 'val_acc': 0.96875, 'test_acc': 0.933, 'overfit_gap': 0.0078125, 'stable_val_score': 0.9609375, 'complexity': 3.0, 'candidate_count': 720, 'baseline_reference_acc': 0.934}

def _num(x, key, default=0.0):
    try:
        value = float(x.get(key, default))
    except Exception:
        return default
    if value != value or value in (float('inf'), float('-inf')):
        return default
    return value

def _tree_000(values):
    if values[2] <= 0.90465101599693298:
        if values[2] <= 0.16301750391721725:
            return -2
        else:
            if values[5] <= 15.318599700927734:
                return -2
            else:
                return -0.79069767441860461
    else:
        if values[2] <= 1.2563350200653076:
            return 0.80000000000000004
        else:
            return 2

def _tree_001(values):
    if values[2] <= 0.90465101599693298:
        if values[3] <= 0.51341401040554047:
            if values[2] <= 0.32988850772380829:
                return -1.5030959022477095
            else:
                return -0.95659781107203623
        else:
            if values[5] <= 15.218849658966064:
                return -1.5488116360940265
            else:
                return 0.16285190419388429
    else:
        if values[2] <= 1.2563350200653076:
            return 0.56926475765016626
        else:
            if values[2] <= 5.4858300685882568:
                return 1.5488116360940258
            else:
                return 1.5488116360940265

def _tree_002(values):
    if values[2] <= 1.0623899698257446:
        if values[2] <= 0.54370397329330444:
            if values[3] <= 0.51341401040554047:
                return -1.2592442970180755
            else:
                return -0.47897008325844076
        else:
            if values[6] <= 6.7781600952148438:
                return 0.78477199976189838
            else:
                return -1.1091926103819523
    else:
        if values[5] <= 36.858449935913086:
            return 0.87256054427691843
        else:
            if values[0] <= 81.464851379394531:
                return 1.3448507753190673
            else:
                return 1.4899887337669837

def _tree_003(values):
    if values[2] <= 1.0623899698257446:
        if values[2] <= 0.54370397329330444:
            if values[2] <= 0.39079199731349945:
                return -0.86973243537042233
            else:
                return -1.3972693393662319
        else:
            if values[3] <= 1.5084699988365173:
                return 0.78527507074506353
            else:
                return -1.0782717612234789
    else:
        if values[4] <= 9.987025260925293:
            return 0.7069400853845148
        else:
            if values[2] <= 1.4053099751472473:
                return 1.3205223000993944
            else:
                return 1.2305683203280835

def _tree_004(values):
    if values[2] <= 1.0623899698257446:
        if values[2] <= 0.16301750391721725:
            if values[3] <= 0.28449299931526184:
                return -1.1845893242487688
            else:
                return -1.2436988259583783
        else:
            if values[5] <= 15.318599700927734:
                return -1.210866292137653
            else:
                return 0.056774770958693356
    else:
        if values[2] <= 1.3919649720191956:
            return 0.56986665710300144
        else:
            if values[6] <= 4.1512000560760498:
                return 1.1589993245854939
            else:
                return 1.2092091513041148

def _tree_005(values):
    if values[2] <= 1.2563350200653076:
        if values[3] <= 2.0278500318527222:
            if values[2] <= 0.54370397329330444:
                return -0.6932314432361093
            else:
                return 0.74434486595236315
        else:
            return -1.681246757142552
    else:
        if values[4] <= 10.45235013961792:
            return 1.145598869658442
        else:
            if values[2] <= 1.6509149670600891:
                return 1.119629775635274
            else:
                return 1.1123759526786421

def _tree_006(values):
    if values[0] <= 101.0625:
        if values[0] <= 98.351600646972656:
            if values[2] <= 0.77354452013969421:
                return -1.5709695154958805
            else:
                return 0.83751070815465289
        else:
            return 1.4304693016757124
    else:
        if values[0] <= 107.85499954223633:
            return -1.2311480303663784
        else:
            if values[2] <= 0.16301750391721725:
                return -1.1110034531784223
            else:
                return 0.12664050884061259

def _tree_007(values):
    if values[2] <= 1.2563350200653076:
        if values[3] <= 2.0278500318527222:
            if values[3] <= 0.51341401040554047:
                return -0.66151766656504163
            else:
                return 0.44032091598408368
        else:
            return -1.4828728983495991
    else:
        if values[5] <= 38.812849044799805:
            return 1.0803380648713743
        else:
            if values[2] <= 1.6509149670600891:
                return 1.0665347732471959
            else:
                return 1.0626076369971611

def _tree_008(values):
    if values[5] <= 15.45930004119873:
        if values[0] <= 104.14450073242188:
            return -1.0855160765976823
        else:
            if values[2] <= 0.16316500306129456:
                return -1.0641147730496845
            else:
                return -1.0936249829134455
    else:
        if values[2] <= 0.16210350394248962:
            if values[0] <= 134.05449676513672:
                return -1.0615554889357515
            else:
                return -1.1036298103913007
        else:
            if values[4] <= 2.6943999528884888:
                return 1.6320301811831186
            else:
                return 0.34438918685883585

def _tree_009(values):
    if values[4] <= 11.089499950408936:
        if values[5] <= 36.179950714111328:
            if values[5] <= 28.148300170898438:
                return -0.51411857637579683
            else:
                return 1.0597176454515667
        else:
            return -1.4328294893089086
    else:
        if values[6] <= 3.2193899154663086:
            if values[2] <= 0.50099149346351624:
                return -1.1403091184305911
            else:
                return 1.1086990678422874
        else:
            return 1.9679698182554415

def predict(x):
    values = [_num(x, feature) for feature in FEATURES]
    score = 0
    score += 0.29999999999999999 * _tree_000(values)
    score += 0.29999999999999999 * _tree_001(values)
    score += 0.29999999999999999 * _tree_002(values)
    score += 0.29999999999999999 * _tree_003(values)
    score += 0.29999999999999999 * _tree_004(values)
    score += 0.29999999999999999 * _tree_005(values)
    score += 0.29999999999999999 * _tree_006(values)
    score += 0.29999999999999999 * _tree_007(values)
    score += 0.29999999999999999 * _tree_008(values)
    score += 0.29999999999999999 * _tree_009(values)
    return 1 if score >= 0.0 else 0
