# Auto-generated by threshold_distiller.py
from __future__ import annotations

FEATURES = ['profile_mean', 'profile_stdev', 'profile_skewness', 'profile_kurtosis', 'dm_snr_mean', 'dm_snr_stdev', 'dm_snr_skewness', 'dm_snr_kurtosis']
MODEL_INFO = {'method': 'threshold_distiller', 'model_family': 'sklearn.GradientBoostingClassifier', 'selection_mode': 'stable_val', 'overfit_penalty': 1.0, 'selected_rank_by_stable_val': 1, 'function': 'fn_p', 'length': 8, 'train_size': 256, 'val_size': 256, 'test_size': 2000, 'seed': 42, 'tabular_representation': 'named_numeric', 'features': ['profile_mean', 'profile_stdev', 'profile_skewness', 'profile_kurtosis', 'dm_snr_mean', 'dm_snr_stdev', 'dm_snr_skewness', 'dm_snr_kurtosis'], 'params': {'n_estimators': 10, 'learning_rate': 0.3, 'max_depth': 2, 'min_samples_leaf': 15}, 'train_acc': 0.9453125, 'val_acc': 0.96484375, 'test_acc': 0.9375, 'overfit_gap': 0.0, 'stable_val_score': 0.96484375, 'complexity': 1.3333333333333333, 'candidate_count': 720, 'baseline_reference_acc': 0.934}

def _num(x, key, default=0.0):
    try:
        value = float(x.get(key, default))
    except Exception:
        return default
    if value != value or value in (float('inf'), float('-inf')):
        return default
    return value

def _tree_000(values):
    if values[2] <= 0.90465101599693298:
        if values[2] <= 0.16301750391721725:
            return -2
        else:
            return -1.2876712328767124
    else:
        if values[6] <= 4.0481150150299072:
            return 2
        else:
            return 1.2

def _tree_001(values):
    if values[2] <= 1.0623899698257446:
        if values[2] <= 0.54370397329330444:
            return -1.3347897491339982
        else:
            return -0.22262149966344294
    else:
        if values[2] <= 1.5539550185203552:
            return 1.2919025983872459
        else:
            return 1.5616089704911293

def _tree_002(values):
    if values[2] <= 1.0623899698257446:
        if values[5] <= 15.45930004119873:
            return -1.4378462039287876
        else:
            return -0.62181348952168825
    else:
        if values[2] <= 1.5539550185203552:
            return 1.0639696760066297
        else:
            return 1.3519092870964631

def _tree_003(values):
    if values[2] <= 0.54370397329330444:
        if values[3] <= 0.51341401040554047:
            return -1.1444168545911493
        else:
            return -0.035409607972617822
    else:
        if values[5] <= 24.964500427246094:
            return -0.50157167018142357
        else:
            return 1.201348009182424

def _tree_004(values):
    if values[2] <= 1.2563350200653076:
        if values[5] <= 15.45930004119873:
            return -1.2324853149893831
        else:
            return -0.32470687494142586
    else:
        if values[6] <= 3.7495900392532349:
            return 1.1617935607664187
        else:
            return 1.2343376460507778

def _tree_005(values):
    if values[2] <= 0.54370397329330444:
        if values[3] <= 0.51341401040554047:
            return -0.95965450922725515
        else:
            return 0.21410644253028188
    else:
        if values[5] <= 24.964500427246094:
            return -0.28861988056449833
        else:
            return 1.0371286939766331

def _tree_006(values):
    if values[2] <= 1.2563350200653076:
        if values[3] <= 1.653439998626709:
            return -0.32351079351826784
        else:
            return -1.269609524506893
    else:
        if values[4] <= 12.474050045013428:
            return 1.1515987940597956
        else:
            return 1.0836725171428956

def _tree_007(values):
    if values[2] <= 0.16301750391721725:
        if values[5] <= 15.65410041809082:
            return -1.0845467824516997
        else:
            return -1.1443150472479033
    else:
        if values[5] <= 15.318599700927734:
            return -1.062095908351854
        else:
            return 0.74371059046886179

def _tree_008(values):
    if values[3] <= 0.51341401040554047:
        if values[2] <= 0.32988850772380829:
            return -0.84967181286078575
        else:
            return 0.14147389012454084
    else:
        if values[5] <= 15.218849658966064:
            return -0.91710754898675595
        else:
            return 0.75608210357399275

def _tree_009(values):
    if values[2] <= 0.16301750391721725:
        if values[5] <= 15.65410041809082:
            return -1.0473170445819706
        else:
            return -1.0927382990310002
    else:
        if values[5] <= 14.801650047302246:
            return -1.0889994299566264
        else:
            return 0.45313936324149962

def predict(x):
    values = [_num(x, feature) for feature in FEATURES]
    score = 0
    score += 0.29999999999999999 * _tree_000(values)
    score += 0.29999999999999999 * _tree_001(values)
    score += 0.29999999999999999 * _tree_002(values)
    score += 0.29999999999999999 * _tree_003(values)
    score += 0.29999999999999999 * _tree_004(values)
    score += 0.29999999999999999 * _tree_005(values)
    score += 0.29999999999999999 * _tree_006(values)
    score += 0.29999999999999999 * _tree_007(values)
    score += 0.29999999999999999 * _tree_008(values)
    score += 0.29999999999999999 * _tree_009(values)
    return 1 if score >= 0.0 else 0
