# Auto-generated by threshold_distiller.py
from __future__ import annotations

FEATURES = ['profile_mean', 'profile_stdev', 'profile_skewness', 'profile_kurtosis', 'dm_snr_mean', 'dm_snr_stdev', 'dm_snr_skewness', 'dm_snr_kurtosis']
MODEL_INFO = {'method': 'threshold_distiller', 'model_family': 'sklearn.GradientBoostingClassifier', 'selection_mode': 'stable_val', 'overfit_penalty': 1.0, 'selected_rank_by_stable_val': 1, 'function': 'fn_p', 'length': 8, 'train_size': 256, 'val_size': 256, 'test_size': 2000, 'seed': 42, 'tabular_representation': 'named_numeric', 'features': ['profile_mean', 'profile_stdev', 'profile_skewness', 'profile_kurtosis', 'dm_snr_mean', 'dm_snr_stdev', 'dm_snr_skewness', 'dm_snr_kurtosis'], 'params': {'n_estimators': 10, 'learning_rate': 0.3, 'max_depth': 2, 'min_samples_leaf': 15}, 'train_acc': None, 'val_acc': None, 'test_acc': 0.936, 'overfit_gap': None, 'stable_val_score': None, 'complexity': 1.3333333333333333, 'candidate_count': 720, 'baseline_reference_acc': 0.934, 'protocol': 'refit_train_val_after_selection', 'train_val_acc': 0.958984375}

def _num(x, key, default=0.0):
    try:
        value = float(x.get(key, default))
    except Exception:
        return default
    if value != value or value in (float('inf'), float('-inf')):
        return default
    return value

def _tree_000(values):
    if values[2] <= 0.74793151021003723:
        if values[2] <= 0.15640399605035782:
            return -2
        else:
            return -1.4437086092715232
    else:
        if values[2] <= 1.050879955291748:
            return 0.59999999999999998
        else:
            return 1.9820627802690582

def _tree_001(values):
    if values[2] <= 0.74793151021003723:
        if values[5] <= 28.524800300598145:
            return -1.4093122974749701
        else:
            return -0.73775322591047676
    else:
        if values[7] <= 40.053949356079102:
            return 1.532428153546505
        else:
            return -0.019461299168785948

def _tree_002(values):
    if values[2] <= 0.86483049392700195:
        if values[5] <= 28.173000335693359:
            return -1.1909180690241588
        else:
            return -0.36444519721480434
    else:
        if values[2] <= 1.2563350200653076:
            return 0.60487247497907104
        else:
            return 1.3565370843408546

def _tree_003(values):
    if values[2] <= 0.74793151021003723:
        if values[2] <= 0.33156551420688629:
            return -1.1049689074707729
        else:
            return -0.30229815100515012
    else:
        if values[5] <= 27.379800796508789:
            return -0.15823037381363281
        else:
            return 1.2030788002019603

def _tree_004(values):
    if values[2] <= 1.050879955291748:
        if values[3] <= 1.6385599970817566:
            return -0.58935613130500786
        else:
            return -1.5841182275458525
    else:
        if values[1] <= 34.040800094604492:
            return 1.0799152074565006
        else:
            return 1.1880858726277845

def _tree_005(values):
    if values[2] <= 0.54561951756477356:
        if values[2] <= 0.15640399605035782:
            return -1.1784797940411886
        else:
            return -0.38756410740612368
    else:
        if values[3] <= 0.983194500207901:
            return 1.7720565031893056
        else:
            return 0.74455917949978745

def _tree_006(values):
    if values[5] <= 27.79365062713623:
        if values[5] <= 15.45930004119873:
            return -1.0517101510100433
        else:
            return -0.40966889355446784
    else:
        if values[2] <= 0.15004450082778931:
            return -1.1651503800104817
        else:
            return 1.0061140183807373

def _tree_007(values):
    if values[2] <= 1.050879955291748:
        if values[3] <= 1.5084699988365173:
            return -0.31970167169502617
        else:
            return -1.4012485788885054
    else:
        if values[2] <= 1.2979999780654907:
            return 0.37934938877066476
        else:
            return 1.0830530992689835

def _tree_008(values):
    if values[2] <= 0.33156551420688629:
        if values[1] <= 42.487600326538086:
            return 0.5745197864424274
        else:
            return -0.86164077620243551
    else:
        if values[2] <= 0.4207255095243454:
            return 2.0525219389245999
        else:
            return 0.36873337591177252

def _tree_009(values):
    if values[5] <= 24.86829948425293:
        if values[0] <= 99.679649353027344:
            return -1.0425945407204791
        else:
            return -0.43502435271687545
    else:
        if values[2] <= 0.15004450082778931:
            return -1.0805416387852234
        else:
            return 0.80051113453370837

def predict(x):
    values = [_num(x, feature) for feature in FEATURES]
    score = 0
    score += 0.29999999999999999 * _tree_000(values)
    score += 0.29999999999999999 * _tree_001(values)
    score += 0.29999999999999999 * _tree_002(values)
    score += 0.29999999999999999 * _tree_003(values)
    score += 0.29999999999999999 * _tree_004(values)
    score += 0.29999999999999999 * _tree_005(values)
    score += 0.29999999999999999 * _tree_006(values)
    score += 0.29999999999999999 * _tree_007(values)
    score += 0.29999999999999999 * _tree_008(values)
    score += 0.29999999999999999 * _tree_009(values)
    return 1 if score >= 0.0 else 0
